language: ruby
rvm:
- 2.6.4
node_js:
- 12.4.0
services:
- postgresql
addons:
  postgresql: '11.4'
before_install:
- sudo add-apt-repository -y ppa:jonathonf/ffmpeg-4
- sudo apt-get update
- sudo apt-get install -y ffmpeg
- sudo apt-get --yes remove postgresql\*
- sudo apt-get install -y postgresql-11 postgresql-client-11
- sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
- sudo service postgresql restart 11
- gem update --system
- gem install bundler
before_script:
- createuser avfacts
- createdb -O avfacts avfacts_test
- yarn install
- bundle exec rails db:migrate webpacker:compile
env:
  global:
    - secure: Ov0wRhQoS0DJIXtH2WVu4ePyLecwYdjyI9+1S5b64yGmFXUyxWgBVOcH7awOFM3J482PN6PLcsXXtC8gh+ZPTS8AzyWEnld0004tu9VMNUCtgtT6bwq5D3hSvZXUL8TvqTkvmJ+DdxJCse/k2SE+UVqbPt+qlPmvRlDeLGY5u17GoqWrc/21j1QnYiipKY55a73zIQwOoeWSKA/wfoiuPS1o4s4vl7ODBW6n3W8G2pF2s8bF8lUtkNwA+8HEK1Gn8rDVajMsTx07tKx5y18O5QKqpNyWFcmyqkChwfTqqD2b2ZOTYATFarJVPYI+Neqht+dKW2ZTLlpkM2PA9vsiCt6j63+Y15UvLVeyAPwEuYz/e1qoPMg4sjYSt8AmXPOVcViY7sOK4j9StuZcyCYdiUzdeUicAdslCIcg8O3UMM2frQ63KV8yD5RCLErSH7Pya3nbG7I6GwOOXb7LDWRgrpzrEPRS7LTpr80+QJBR8QrvG30DsvPwYiHeEGIMWN6h7BR6jFbMtq632W0pvCtjLgBKmzwwvAjOvvDZLdbvlgND1uyGjQJUZ9JAlmpWq7SKVJqHkh3J1p6n1Czuyr4Sq3ruTLTvCZik5tUDItKAm/ufh9D7gZhatTr2cOYsSQ//5Qp95+pvQaYhlVL2tNoRSXuJn5ebf0sK/w6loy8ssCc=
    - RAILS_TEST_DB_USERNAME=postgres
    - PGUSER=postgres
