---
title: AvFacts - Aviation knowledge without limits
language: en
copyright: ©2017 Tim Morgan
webmaster: avfacts@timothymorgan.info (Tim Morgan)
summary: Fascinating aviation knowledge, civilian and military, big and small.
description: |-
  AvFacts is a podcast by Tim Morgan that introduces you to a new aviation topic
  with each episode. I’ll walk you through interesting topics covering aircraft
  big and small, civilian and military, airplanes and helicopters, and
  everything in between. As long as it’s interesting and has to do with
  aviation, I’ll talk about it on AvFacts.
subtitle: Aviation knowledge without limits
owner:
  name: Tim Morgan
  email: avfacts@timothymorgan.info
author: Tim Morgan
explicit: false
itunes_category:
  "Games & Hobbies": Aviation
