# PostgreSQL. Versions 9.1 and up are supported.

common: &common
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: avfacts

development:
  <<: *common
  database: avfacts_development

test:
  <<: *common
  database: avfacts_test

production:
  <<: *common
  database: avfacts_production
