---
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
production:
  :concurrency: 20
:queues:
- avfacts_development_default
- avfacts_development_active_storage_analysis
- avfacts_development_active_storage_purge
